spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mercari
    username: postgres
    password: postgres

logging:
  file:
    path: /Users/moritasoshi/Workspace/spring-boot-workspace/ex-math-data/src/main/resources/log
  level:
    root: off
    com.example.common.LogUtils: info