spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mercari
    username: postgres
    password: postgres

logging:
  file:
    path: ../log
  level:
    root: off
    com.example.common.LogUtils: info